// React Query key factories -- keep all query keys centralized so cache
// invalidation stays consistent across the app.
export const queryKeys = {
  attendance: ["attendance"] as const,
  events: ["events"] as const,
  profile: (userId: string) => ["profile", userId] as const,
  cms: (section: string) => ["cms", section] as const,
  admissions: ["admissions"] as const,
  admission: (id: string) => ["admissions", id] as const,
  blogPosts: ["blog-posts"] as const,
  blogPost: (slug: string) => ["blog-posts", slug] as const,
  blogAuthor: (slug: string) => ["blog-author", slug] as const,
  blogAuthors: ["blog-authors"] as const,
  galleryAlbums: ["gallery-albums"] as const,
  galleryAlbum: (id: string) => ["gallery-albums", id] as const,
  eventsList: ["events-list"] as const,
  event: (id: string) => ["events-list", id] as const,
  eventRsvps: (eventId: string) => ["event-rsvps", eventId] as const,
  students: (parentUserId?: string) => ["students", parentUserId ?? "all"] as const,
  student: (id: string) => ["students", "detail", id] as const,
  attendanceRecords: (studentId: string, month?: string) => ["attendance-records", studentId, month ?? "all"] as const,
  invoices: (studentId?: string) => ["invoices", studentId ?? "all"] as const,
  payments: (studentId?: string) => ["payments", studentId ?? "all"] as const,
  announcements: ["announcements"] as const,
  downloadDocuments: ["download-documents"] as const,
  homework: (className?: string) => ["homework", className ?? "all"] as const,
  activityLogs: (studentId: string) => ["activity-logs", studentId] as const,
  conversations: (userId?: string) => ["conversations", userId ?? "all"] as const,
  messages: (conversationId: string) => ["messages", conversationId] as const,
  progressReports: (studentId?: string) => ["progress-reports", studentId ?? "all"] as const,
  teacherAttendance: (className: string, date: string) => ["teacher-attendance", className, date] as const,
  classActivityLogs: (studentIds: string) => ["class-activity-logs", studentIds] as const,
  managedUsers: (role?: string) => ["managed-users", role ?? "all"] as const,
  rolePermissions: ["role-permissions"] as const,
  auditLogs: ["audit-logs"] as const,
  systemSettings: ["system-settings"] as const,
  adminStats: ["admin-stats"] as const,
  allStudents: ["all-students"] as const,
  allInvoices: ["all-invoices"] as const,
};
